import type { ProductSnapshot } from "../shared/product-types";

export const productTypeLabels: Record<string, string> = {
  project: "项目",
  goal: "目标",
  module: "模块",
  requirement: "需求",
  design: "设计",
  plan: "计划",
  change: "变化",
  assessment: "交付报告",
  discussion: "讨论",
  unknown: "未知条目",
};
export const productLabels: Record<string, string> = {
  current: "当前范围",
  planned: "后续范围",
  candidate: "候选范围",
  retired: "退出范围",
  proposed: "提案",
  adopted: "已采用",
  included: "纳入安排",
  deferred: "延期",
  withdrawn: "撤回",
  initial: "原定",
  added: "后加工作",
  unknown: "未知",
  declared: "明确声明",
  inferred: "推断关联",
  active: "有效关联",
  dismissed: "已否定关联",
  implementation: "实施",
  repair: "修复",
  verification: "验证",
  exploration: "探索",
  reference: "参考",
  "none-reported": "报告未实施",
  "partial-reported": "报告部分实施",
  "delivered-reported": "报告已交付",
  "not-run-reported": "报告未运行",
  "failure-reported": "报告失败",
  "pass-reported": "报告通过",
  "mixed-reported": "报告结果混合",
  partial: "部分盘点",
  reconciled: "所列来源已对账",
  supports: "支持目标",
  part_of: "业务归属",
  addresses: "方案覆盖需求",
  depends_on: "业务 / 方案依赖",
  replaces: "替代",
  derived_from: "演进自",
  discusses: "相关讨论",
  references: "普通参考",
};
export const productStatusLabels: Record<ProductSnapshot["status"], string> = {
  disabled: "PRODUCT 未启用",
  missing: "未发现 PRODUCT 入口",
  excluded: "PRODUCT 入口被排除",
  unavailable: "PRODUCT 读取失败",
  unsupported: "不支持的 PRODUCT 版本",
  partial: "PRODUCT 部分可用",
  ready: "PRODUCT 已读取",
  empty: "PRODUCT 有效空结果",
};
